# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               RecSys Blog
tagline:             Por Jaime Castro
description:         Comentarios personales sobre artículos del área de sistemas recomendadores.
url:                 ''
baseurl:             '/recsysblog'
paginate:            5

# About/contact
author:
  name:              Jaime Castro
  url:               https://twitter.com/sirjaimecastro
  email:             jecastro1@uc.cl

# Custom vars
version:             1.0.0

# Build settings
markdown: kramdown
force_polling: true
