# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RecSys Blog
email: jecastro1@uc.cl
description: > # this means to ignore newlines until "baseurl:"
  Comentarios personales sobre artículos del área de sistemas recomendadores.
baseurl: "/recsysblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: sirjaimecastro
github_username:  jecastro1

# Build settings
markdown: kramdown
force_polling: true
